//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string course_code { get; set; }
        public Nullable<int> topic_id { get; set; }
        public string content_description { get; set; }
        public Nullable<int> filesize { get; set; }
        public string videoname { get; set; }
    
        public virtual course course { get; set; }
        public virtual topic topic { get; set; }
        public virtual user user { get; set; }
    }
}
