//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_reply
    {
        public int id { get; set; }
        public Nullable<int> replied_by { get; set; }
        public Nullable<int> feedback_id { get; set; }
        public string reply { get; set; }
    
        public virtual feedback feedback { get; set; }
    }
}
