//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public topic()
        {
            this.contents = new HashSet<content>();
            this.quizs = new HashSet<quiz>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string course_code { get; set; }
        public string topic_name { get; set; }
        public Nullable<int> topic_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<content> contents { get; set; }
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quiz> quizs { get; set; }
        public virtual user user { get; set; }
    }
}
